dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test store
deploy:
  provider: heroku
  app: prueba1jsvruimun
  strategy: git
  api_key:
    secure: V0bJfIlQDsuzgT6+Ure5wCVtXIlGaRdHauu7B0aLOTDcz7OFcDHdMfN3d8nxwgfwROM/MWQCC49s/G4WCOYao6vkIdUt/CXyoI5zMCRqYGUI/n7iQEcIlQkfQXUyVbfyK6UxtcB7ayuOnwbl6ch5wGEzvEQ3NDqKUmvYFCj2EhnV7n8ytkoR9ufilfhXicuge+XnfiQG7IgVyjnTO9VSztqGKfQsezOCptWfoiHTi19FQXvyroDJmlAZ0j9hH/2fhEGMWoBmpijzbwgN+lZYRm2MlBHK54DLBIP2SLTbIHwyWypmi6F1U0ac2fq0Xi7KHObAwAE/rJV5eL4476rL+nW08wbcBnnXYYQQSOo7eNrG1QpeJcotFcLdtI87qgbN+QdbZUSgeJi2f/SAEAMWV/t3HC6NT8LR6KgsAhlTgTLEsl/N6O/wRwgx7C9XC1RT/XcuPiGkO15k2F05/xys8iZvzkAtgtGDm9CkdM4rYIu/JZoGUqG9Pb3RJNNUfGvaMgAjYYDDQzclW9sQyeTv5oaO+7EEiOTUly8411pVRgeB15MiRj3zZ4SdDsu0CIb2uEsGNFCYaH3TJ/ciwr7r5Q7ERgpukyLcsdLD+EVZdXYPZs3GTYzHthWLpM71ZggeEKIdkSQp2EWYbwoDVOHtSWb7uyJJ6SWVymH5lMBNhFU=
